package ru.vafeen.castcastle.processor.processing.utils


internal fun copyright() = """
        Auto-generated by Cast Castle. Do not edit.

        Apache-2.0 license

        Contact: [vafeen](https://github.com/vafeen)
        """.trimIndent()
